rps-31/oAuth
Halkida/rock.paper.scissors pull request #33
Opened 2021-12-27 08:30 UTC by AnastasiiaRyabchikova

2021-12-28 06:00 UTC, 1kazakov approved these changes

2021-12-28 07:17 UTC, inham130 approved these changes

2021-12-29 13:56 UTC, bercly0b commented on src/components/App/index.ts
> +export default withOAuthCheck(
давай compose из редакса заюзаем?

2021-12-29 14:02 UTC, bercly0b commented on src/hocs/with-oauth-check.tsx
> +      <Spinner /> :
мне не нравится идея для любого открытия страницы показывать спиннер.
у нас же ситуация когда есть code (после oauth) - это частный случай. а из-за частного случая менять логику рендера всего приложения на каждый раз, звучит не очень) 

мы же можем заранее проверить что у нас нету code и тогда просто вернуть `Component` без изменения логики рендера

2021-12-29 14:03 UTC, bercly0b requested changes
https://github.com/Halkida/rock.paper.scissors/pull/33/files#r776341156

2022-01-09 07:42 UTC, bercly0b approved these changes

2022-01-09 07:42 UTC, merged